version: '3.8'

services:
  bot:
    build: .
    container_name: hhru-go-bot
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - REDIS_ADDR=172.17.0.2:6379
    network_mode: bridge